### ISSUE TITLE
Listener fails to receive new events after an error

### ISSUE THREAD

**Issue by dropout1692** [dropout1692/BeelzeBot#1]
Version: 0.0.2-RELEASE

Listener stops receiving new events after it fails to handle an event.

`io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'discord.com' failed to resolve 'discord.com'`

**Comment by dropout1692** [comment]
New handling patched in, hopefully fixed in 0.0.3-RELEASE.
https://github.com/dropout1692/BeelzeBot/releases/tag/0.0.3-RELEASE

**Comment by dropout1692** [comment]
Issue still present in 0.0.3-RELEASE. Fix failed.

Full trace:

> 2021-03-29 19:59:24.516 ERROR 138692 --- [undedElastic-11] w.d.b.listeners.UserMessageListener      : Unable to handle MessageCreateEvent! Attempting to continue..

>io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'discord.com' failed to resolve 'discord.com'
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1013) ~[netty-resolver-dns-4.1.59.Final.jar!/:4.1.59.Final]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        |_ checkpoint ⇢ Request to GET /channels/776955332235755541 [RequestStream]
        |_ checkpoint ⇢ Request to GET /channels/776955332235755541 [DefaultRouter]
Stack trace:
                at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1013) ~[netty-resolver-dns-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:966) ~[netty-resolver-dns-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:414) ~[netty-resolver-dns-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63) ~[netty-resolver-dns-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:463) ~[netty-resolver-dns-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:225) ~[netty-resolver-dns-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177) ~[netty-resolver-dns-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-transport-native-epoll-4.1.59.Final-linux-x86_64.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.59.Final.jar!/:4.1.59.Final]
                at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/127.0.0.53:53] query via UDP timed out after 5000 milliseconds (no stack trace available)

**Comment by dropout1692** [comment]
Upgraded to Discord4j 3.1.4 in 0.1.0-SNAPSHOT. Testing in progress.

**Comment by dropout1692** [comment]
Stress test & 24hr test complete. Looks like updating to Discord4J 3.1.4 solved the issue. Fix will be released in [1.0.0-RELEASE](https://github.com/dropout1692/BeelzeBot/milestone/1). Closing issue for now.
